### ISSUE TITLE
Plugin Spec Doesn't Support Recursive Type Referencing

### ISSUE THREAD

**Issue by t0astt** [komand/plugin-sdk-python#50]
The plugin.spec.yaml parser does not support recursive type referencing. This is necessary for certain data types used in APIs, such as Resilient.

The following will fail to parse:
```
types:
  CommentDTO:
    name:
      type: string
    children:
      type: CommentDTO
```

Temporary workaround is to make these types reference object.
